# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kletska/files/hse/avs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kletska/files/hse/avs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kletska/files/hse/avs/CMakeFiles /home/kletska/files/hse/avs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kletska/files/hse/avs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named task01

# Build rule for target.
task01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task01
.PHONY : task01

# fast build rule for target.
task01/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/build
.PHONY : task01/fast

container.o: container.cpp.o
.PHONY : container.o

# target to build an object file
container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/container.cpp.o
.PHONY : container.cpp.o

container.i: container.cpp.i
.PHONY : container.i

# target to preprocess a source file
container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/container.cpp.i
.PHONY : container.cpp.i

container.s: container.cpp.s
.PHONY : container.s

# target to generate assembly for a file
container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/container.cpp.s
.PHONY : container.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/main.cpp.s
.PHONY : main.cpp.s

plain.o: plain.cpp.o
.PHONY : plain.o

# target to build an object file
plain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/plain.cpp.o
.PHONY : plain.cpp.o

plain.i: plain.cpp.i
.PHONY : plain.i

# target to preprocess a source file
plain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/plain.cpp.i
.PHONY : plain.cpp.i

plain.s: plain.cpp.s
.PHONY : plain.s

# target to generate assembly for a file
plain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/plain.cpp.s
.PHONY : plain.cpp.s

ship.o: ship.cpp.o
.PHONY : ship.o

# target to build an object file
ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/ship.cpp.o
.PHONY : ship.cpp.o

ship.i: ship.cpp.i
.PHONY : ship.i

# target to preprocess a source file
ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/ship.cpp.i
.PHONY : ship.cpp.i

ship.s: ship.cpp.s
.PHONY : ship.s

# target to generate assembly for a file
ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/ship.cpp.s
.PHONY : ship.cpp.s

train.o: train.cpp.o
.PHONY : train.o

# target to build an object file
train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/train.cpp.o
.PHONY : train.cpp.o

train.i: train.cpp.i
.PHONY : train.i

# target to preprocess a source file
train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/train.cpp.i
.PHONY : train.cpp.i

train.s: train.cpp.s
.PHONY : train.s

# target to generate assembly for a file
train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/train.cpp.s
.PHONY : train.cpp.s

transport.o: transport.cpp.o
.PHONY : transport.o

# target to build an object file
transport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/transport.cpp.o
.PHONY : transport.cpp.o

transport.i: transport.cpp.i
.PHONY : transport.i

# target to preprocess a source file
transport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/transport.cpp.i
.PHONY : transport.cpp.i

transport.s: transport.cpp.s
.PHONY : transport.s

# target to generate assembly for a file
transport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task01.dir/build.make CMakeFiles/task01.dir/transport.cpp.s
.PHONY : transport.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... task01"
	@echo "... container.o"
	@echo "... container.i"
	@echo "... container.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... plain.o"
	@echo "... plain.i"
	@echo "... plain.s"
	@echo "... ship.o"
	@echo "... ship.i"
	@echo "... ship.s"
	@echo "... train.o"
	@echo "... train.i"
	@echo "... train.s"
	@echo "... transport.o"
	@echo "... transport.i"
	@echo "... transport.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

